# GENERATED by tools/gen_contracts.py — do not edit. Run `make contracts`.
from __future__ import annotations

from sa_contracts.events.matching_link_confirmed import MatchingLinkConfirmed
from sa_contracts.events.offer_effective_price_changed import OfferEffectivePriceChanged
from sa_contracts.events.supplier_offer_price_changed import SupplierOfferPriceChanged
from sa_contracts.events.supplier_product_discovered import SupplierProductDiscovered
from sa_contracts.events.sync_job_requested import SyncJobRequested
from sa_contracts.spec import EventSpec

EVENT_REGISTRY: dict[str, EventSpec] = {
    "matching.link.confirmed": EventSpec(
        event_type="matching.link.confirmed",
        model=MatchingLinkConfirmed,
        topic="sa.matching.link",
        dataschema="https://contracts.sa.internal/events/matching.link.confirmed.json",
    ),
    "offer.effective-price.changed": EventSpec(
        event_type="offer.effective-price.changed",
        model=OfferEffectivePriceChanged,
        topic="sa.offer.effective-price",
        dataschema="https://contracts.sa.internal/events/offer.effective-price.changed.json",
    ),
    "supplier.offer.price-changed": EventSpec(
        event_type="supplier.offer.price-changed",
        model=SupplierOfferPriceChanged,
        topic="sa.supplier.offer",
        dataschema="https://contracts.sa.internal/events/supplier.offer.price-changed.json",
    ),
    "supplier.product.discovered": EventSpec(
        event_type="supplier.product.discovered",
        model=SupplierProductDiscovered,
        topic="sa.supplier.product",
        dataschema="https://contracts.sa.internal/events/supplier.product.discovered.json",
    ),
    "sync.job.requested": EventSpec(
        event_type="sync.job.requested",
        model=SyncJobRequested,
        topic="sa.sync.job",
        dataschema="https://contracts.sa.internal/events/sync.job.requested.json",
    ),
}

__all__ = [
    "EVENT_REGISTRY",
    "MatchingLinkConfirmed",
    "OfferEffectivePriceChanged",
    "SupplierOfferPriceChanged",
    "SupplierProductDiscovered",
    "SyncJobRequested",
]
