"""initial schema

Revision ID: f59bc0958fe5
Revises:
Create Date: 2026-07-12 13:59:59.082530
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f59bc0958fe5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "price_history_processed_events",
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "price_point",
        sa.Column("offer_id", sa.String(length=26), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("supplier_account_id", sa.String(length=26), nullable=False),
        sa.Column("supplier_product_id", sa.String(length=26), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_uah", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("offer_id", "ts"),
    )
    op.create_index(
        op.f("ix_price_point_supplier_product_id"),
        "price_point",
        ["supplier_product_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Make price_point a TimescaleDB hypertable when the extension is available (production).
    # On plain Postgres or SQLite (tests) this is a no-op — the table works identically.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        available = bind.execute(
            sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb'")
        ).first()
        if available is not None:
            op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
            op.execute(
                "SELECT create_hypertable('price_point', 'ts', "
                "if_not_exists => TRUE, migrate_data => TRUE)"
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_point_supplier_product_id"), table_name="price_point")
    op.drop_table("price_point")
    op.drop_table("price_history_processed_events")
    op.drop_table("outbox")
    # ### end Alembic commands ###
