"""initial schema

Revision ID: 4656245eb33e
Revises:
Create Date: 2026-07-12 13:58:14.247630
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4656245eb33e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "product_canonical_link",
        sa.Column("supplier_product_id", sa.String(length=26), nullable=False),
        sa.Column("canonical_product_id", sa.String(length=26), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("supplier_product_id"),
    )
    op.create_index(
        op.f("ix_product_canonical_link_canonical_product_id"),
        "product_canonical_link",
        ["canonical_product_id"],
        unique=False,
    )
    op.create_table(
        "supplier_product",
        sa.Column("supplier_product_id", sa.String(length=26), nullable=False),
        sa.Column("supplier_code", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("external_code", sa.String(length=128), nullable=True),
        sa.Column("articul", sa.String(length=255), nullable=True),
        sa.Column("gtin", sa.String(length=14), nullable=True),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("supplier_category_id", sa.String(length=64), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("raw_identifiers", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("supplier_product_id"),
        sa.UniqueConstraint("supplier_code", "external_id"),
    )
    op.create_index(op.f("ix_supplier_product_gtin"), "supplier_product", ["gtin"], unique=False)
    op.create_index(
        op.f("ix_supplier_product_supplier_code"),
        "supplier_product",
        ["supplier_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_supplier_product_supplier_code"), table_name="supplier_product")
    op.drop_index(op.f("ix_supplier_product_gtin"), table_name="supplier_product")
    op.drop_table("supplier_product")
    op.drop_index(
        op.f("ix_product_canonical_link_canonical_product_id"), table_name="product_canonical_link"
    )
    op.drop_table("product_canonical_link")
    op.drop_table("processed_events")
    op.drop_table("outbox")
    # ### end Alembic commands ###
