# generated by datamodel-codegen:
#   filename:  catalog.product.updated.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Status(Enum):
    confirmed = "confirmed"
    draft = "draft"


class CatalogProductUpdated(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    canonical_product_id: Annotated[
        str,
        Field(description="ULID of the canonical (platform) product this card describes."),
    ]
    title: Annotated[
        str,
        Field(description="Canonical product title, derived from its member supplier products."),
    ]
    brand: Annotated[str | None, Field(description="Canonical brand, if a member carries one.")] = (
        None
    )
    gtin: Annotated[
        str | None,
        Field(
            description="Representative normalized GTIN-14 of the product, if any member has one."
        ),
    ] = None
    status: Annotated[
        Status,
        Field(
            description="Card status. Cards are emitted for confirmed canonicals; 'draft' reserved for future flows."
        ),
    ]
    supplier_product_ids: Annotated[
        list[str],
        Field(description="Supplier products currently linked to this canonical (its members)."),
    ]
    attributes: Annotated[
        dict[str, Any] | None,
        Field(
            description="Merged product attributes aggregated from the member supplier products."
        ),
    ] = None
    updated_at: Annotated[AwareDatetime, Field(description="When the card was last rebuilt (UTC).")]
