# generated by datamodel-codegen:
#   filename:  matching.link.confirmed.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Method(Enum):
    gtin_auto = "gtin_auto"
    rag_suggested = "rag_suggested"
    manual = "manual"


class MatchingLinkConfirmed(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    link_id: str
    supplier_product_id: str
    canonical_product_id: str
    method: Annotated[
        Method,
        Field(
            description="How the candidate was produced. gtin_auto links are auto-confirmed; others require an operator."
        ),
    ]
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    decided_by: Annotated[str, Field(description="Operator user id, or 'system' for gtin_auto")]
    decided_at: AwareDatetime
    previous_canonical_product_id: Annotated[
        str | None,
        Field(
            description="Set when the confirmation re-links the product from another canonical (merge/split flows)"
        ),
    ] = None
