# generated by datamodel-codegen:
#   filename:  offer.effective-price.changed.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Cause(StrEnum):
    price_changed = "price_changed"
    terms_changed = "terms_changed"


class OfferEffectivePriceChanged(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    offer_id: Annotated[
        str,
        Field(description="ULID of the Offer (supplier_account x supplier_product)"),
    ]
    supplier_account_id: Annotated[
        str, Field(description="ULID of the account whose terms produced this price")
    ]
    supplier_product_id: Annotated[str, Field(description="ULID of the product this offer prices")]
    old_effective_price_uah: Annotated[
        str | None,
        Field(
            description="Previous effective UAH price as a decimal string; null on first pricing",
            pattern="^[0-9]+\\.[0-9]{1,4}$",
        ),
    ] = None
    new_effective_price_uah: Annotated[
        str,
        Field(
            description="New effective UAH price as a decimal string (never float)",
            pattern="^[0-9]+\\.[0-9]{1,4}$",
        ),
    ]
    base_price: Annotated[
        str,
        Field(
            description="Supplier base price this effective price was computed from, in `currency`",
            pattern="^[0-9]+\\.[0-9]{1,4}$",
        ),
    ]
    currency: Annotated[
        str,
        Field(
            description="ISO-4217 code of `base_price` (the account settlement currency)",
            pattern="^[A-Z]{3}$",
        ),
    ]
    observed_at: Annotated[
        AwareDatetime,
        Field(
            description="When the input that moved the effective price was observed (base price observation, or terms change time)"
        ),
    ]
    cause: Annotated[
        Cause,
        Field(
            description="What moved the effective price: a supplier base-price change or an account-terms change"
        ),
    ]
