# generated by datamodel-codegen:
#   filename:  supplier.product.discovered.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class SupplierProductDiscovered(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    supplier_product_id: Annotated[str, Field(description="Internal ULID of the SupplierProduct")]
    supplier_code: Annotated[str, Field(description="Supplier short code, e.g. 'brain'")]
    external_id: Annotated[str, Field(description="Supplier's own product id (Brain: productID)")]
    external_code: Annotated[
        str | None, Field(description="Supplier's product code (Brain: product_code)")
    ] = None
    articul: Annotated[
        str | None,
        Field(description="Manufacturer part number as provided by supplier"),
    ] = None
    gtin: Annotated[
        str | None,
        Field(
            description="Normalized GTIN-14 (from EAN/UPC), null if absent or checksum-invalid",
            pattern="^[0-9]{14}$",
        ),
    ] = None
    raw_identifiers: Annotated[
        dict[str, str] | None,
        Field(description="Original identifier strings before normalization (ean, upc, ...)"),
    ] = None
    name: str
    brand: str | None = None
    supplier_category_id: str | None = None
    attributes: Annotated[
        dict[str, Any] | None,
        Field(description="Normalized attribute map (name -> value(s)) from supplier options"),
    ] = None
    content_hash: Annotated[
        str | None,
        Field(description="Hash of normalized content, used for change detection"),
    ] = None
    sync_job_id: Annotated[str, Field(description="Sync job that produced this event")]
