# generated by datamodel-codegen:
#   filename:  supplier.offer.price-changed.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class SupplierOfferPriceChanged(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    offer_id: Annotated[
        str,
        Field(description="ULID of the Offer (supplier_account x supplier_product)"),
    ]
    supplier_account_id: str
    supplier_product_id: str
    old_price: Annotated[
        str | None,
        Field(
            description="Previous base price as decimal string; null on first observation",
            pattern="^[0-9]+\\.[0-9]{1,4}$",
        ),
    ] = None
    new_price: Annotated[
        str,
        Field(
            description="New base price as decimal string (never float)",
            pattern="^[0-9]+\\.[0-9]{1,4}$",
        ),
    ]
    currency: Annotated[
        str,
        Field(
            description="ISO-4217, supplier settlement currency of this account",
            pattern="^[A-Z]{3}$",
        ),
    ]
    price_uah: Annotated[str | None, Field(pattern="^[0-9]+\\.[0-9]{1,4}$")] = None
    rrp_uah: Annotated[
        str | None,
        Field(
            description="Recommended retail price if supplier provides it",
            pattern="^[0-9]+\\.[0-9]{1,4}$",
        ),
    ] = None
    observed_at: Annotated[
        AwareDatetime,
        Field(description="When the connector observed the new value at the supplier"),
    ]
    sync_job_id: str
