# generated by datamodel-codegen:
#   filename:  sync.job.requested.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Kind(Enum):
    products = "products"
    offers = "offers"
    all = "all"


class SyncJobRequested(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    supplier_code: Annotated[
        str,
        Field(description="Supplier short code the connector is registered under, e.g. 'brain'"),
    ]
    account_id: Annotated[
        str,
        Field(
            description="Account (ULID) to sync — a supplier can have several with different terms"
        ),
    ]
    credentials_ref: Annotated[
        str | None,
        Field(
            description="Vault path to the account's credentials (a pointer, never the secret itself)"
        ),
    ] = None
    settlement_currency: Annotated[
        str, Field(description="ISO-4217 code the account settles in, e.g. 'USD'")
    ]
    kind: Annotated[
        Kind,
        Field(
            description="What to sync: the product catalog, this account's offers (prices/stock), or both"
        ),
    ]
    sync_job_id: Annotated[
        str, Field(description="ULID correlating every event produced by this sync run")
    ]
    requested_at: Annotated[
        AwareDatetime, Field(description="When the sync was requested (UTC, ISO 8601)")
    ]
