"""initial schema

Revision ID: 60f2d4a41ead
Revises:
Create Date: 2026-07-12 13:59:57.657852
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "60f2d4a41ead"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer",
        sa.Column("offer_id", sa.String(length=26), nullable=False),
        sa.Column("supplier_account_id", sa.String(length=26), nullable=False),
        sa.Column("supplier_product_id", sa.String(length=26), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_uah", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("rrp_uah", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("offer_id"),
    )
    op.create_index(
        op.f("ix_offer_supplier_account_id"), "offer", ["supplier_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_offer_supplier_product_id"), "offer", ["supplier_product_id"], unique=False
    )
    op.create_table(
        "offer_processed_events",
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox")
    op.drop_table("offer_processed_events")
    op.drop_index(op.f("ix_offer_supplier_product_id"), table_name="offer")
    op.drop_index(op.f("ix_offer_supplier_account_id"), table_name="offer")
    op.drop_table("offer")
    # ### end Alembic commands ###
