"""initial schema

Revision ID: 3a9469460280
Revises:
Create Date: 2026-07-12 13:59:56.811372
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3a9469460280"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer_identity",
        sa.Column("supplier_account_id", sa.String(length=26), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("offer_id", sa.String(length=26), nullable=False),
        sa.Column("last_price", sa.String(length=32), nullable=False),
        sa.Column("last_currency", sa.String(length=3), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("supplier_account_id", "external_id"),
        sa.UniqueConstraint("offer_id"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supplier_product_identity",
        sa.Column("supplier_code", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("supplier_product_id", sa.String(length=26), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("supplier_code", "external_id"),
        sa.UniqueConstraint("supplier_product_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supplier_product_identity")
    op.drop_table("outbox")
    op.drop_table("offer_identity")
    # ### end Alembic commands ###
