"""Regenerate typed event models from contracts/events/*.json (the source of truth).

For each event schema this generates a Pydantic v2 model module under
``libs/contracts/src/sa_contracts/events/`` and a ``registry.py`` binding every event
``type`` to its model, Kafka topic and dataschema URI. Generated files are then
formatted with ruff. The JSON Schemas remain the source of truth — never hand-edit the
generated models; change the schema and rerun ``make contracts``.

Usage: uv run python tools/gen_contracts.py
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EVENTS_DIR = ROOT / "contracts" / "events"
PKG_DIR = ROOT / "libs" / "contracts" / "src" / "sa_contracts"
MODELS_DIR = PKG_DIR / "events"

CODEGEN_ARGS = [
    "--input-file-type",
    "jsonschema",
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--target-python-version",
    "3.12",
    "--use-annotated",
    "--field-constraints",
    "--use-standard-collections",
    "--use-union-operator",
    "--disable-timestamp",
    "--formatters",
    "black",
    "isort",
]

DO_NOT_EDIT = "# GENERATED by tools/gen_contracts.py — do not edit. Run `make contracts`.\n"


def _tokens(title: str) -> list[str]:
    return [tok for tok in re.split(r"[.\-]", title) if tok]


def class_name(title: str) -> str:
    """Derive the model class name datamodel-codegen produces from a schema title."""
    return "".join(tok.capitalize() for tok in _tokens(title))


def module_name(title: str) -> str:
    return title.replace(".", "_").replace("-", "_")


def topic_for(title: str) -> str:
    domain, entity = title.split(".")[:2]
    return f"sa.{domain}.{entity}"


def _run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True, cwd=ROOT)  # noqa: S603 -- fixed argv built from repo files


def generate_model(schema_path: Path) -> None:
    title = json.loads(schema_path.read_text(encoding="utf-8"))["title"]
    out = MODELS_DIR / f"{module_name(title)}.py"
    _run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(schema_path),
            "--output",
            str(out),
            *CODEGEN_ARGS,
        ]
    )


def write_registry(schemas: list[Path]) -> None:
    entries: list[tuple[str, str, str, str, str]] = []
    for schema_path in schemas:
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        title = schema["title"]
        entries.append(
            (
                title,
                module_name(title),
                class_name(title),
                topic_for(title),
                schema["$id"],
            )
        )

    lines = [DO_NOT_EDIT, "from __future__ import annotations\n\n"]
    for _title, module, cls, _topic, _schema in entries:
        lines.append(f"from sa_contracts.events.{module} import {cls}\n")
    lines.append("from sa_contracts.spec import EventSpec\n\n\n")
    lines.append("EVENT_REGISTRY: dict[str, EventSpec] = {\n")
    for title, _module, cls, topic, dataschema in entries:
        lines.append(
            f'    "{title}": EventSpec(\n'
            f'        event_type="{title}",\n'
            f"        model={cls},\n"
            f'        topic="{topic}",\n'
            f'        dataschema="{dataschema}",\n'
            f"    ),\n"
        )
    lines.append("}\n\n")
    exported = ["EVENT_REGISTRY", *sorted(cls for _t, _m, cls, _tp, _s in entries)]
    lines.append("__all__ = [\n")
    lines.extend(f'    "{name}",\n' for name in exported)
    lines.append("]\n")
    (PKG_DIR / "registry.py").write_text("".join(lines), encoding="utf-8")


def main() -> int:
    schemas = sorted(p for p in EVENTS_DIR.glob("*.json") if not p.name.startswith("_"))
    if not schemas:
        print("no event schemas found", file=sys.stderr)
        return 1

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    (MODELS_DIR / "__init__.py").write_text(DO_NOT_EDIT, encoding="utf-8")

    for schema_path in schemas:
        generate_model(schema_path)
    write_registry(schemas)

    # Canonicalize formatting so generated files satisfy the repo's ruff config.
    _run([sys.executable, "-m", "ruff", "check", "--fix", "--quiet", str(PKG_DIR)])
    _run([sys.executable, "-m", "ruff", "format", "--quiet", str(PKG_DIR)])
    print(f"generated {len(schemas)} event models + registry into {PKG_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
