"""initial schema

Revision ID: 80926a91aa7f
Revises:
Create Date: 2026-07-12 13:59:58.401473
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "80926a91aa7f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_product",
        sa.Column("canonical_product_id", sa.String(length=26), nullable=False),
        sa.Column("gtin", sa.String(length=14), nullable=True),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("canonical_product_id"),
    )
    op.create_index(
        op.f("ix_canonical_product_brand"), "canonical_product", ["brand"], unique=False
    )
    op.create_index(op.f("ix_canonical_product_gtin"), "canonical_product", ["gtin"], unique=True)
    op.create_table(
        "matching_processed_events",
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_link",
        sa.Column("supplier_product_id", sa.String(length=26), nullable=False),
        sa.Column("canonical_product_id", sa.String(length=26), nullable=False),
        sa.Column("link_id", sa.String(length=26), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_by", sa.String(length=64), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("supplier_product_id"),
        sa.UniqueConstraint("link_id"),
    )
    op.create_index(
        op.f("ix_product_link_canonical_product_id"),
        "product_link",
        ["canonical_product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_link_canonical_product_id"), table_name="product_link")
    op.drop_table("product_link")
    op.drop_table("outbox")
    op.drop_table("matching_processed_events")
    op.drop_index(op.f("ix_canonical_product_gtin"), table_name="canonical_product")
    op.drop_index(op.f("ix_canonical_product_brand"), table_name="canonical_product")
    op.drop_table("canonical_product")
    # ### end Alembic commands ###
